name: Build Flatpak

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files in repository
        run: |
          echo "Listing files in the repository root:"
          ls -al

      - name: Set up Flatpak
        run: |
          sudo apt update
          sudo apt install -y flatpak flatpak-builder

      - name: Verify Flatpak Installation
        run: |
          flatpak --version
          flatpak-builder --version

      - name: Add Flathub remote
        run: |
          sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

      - name: Build Flatpak
        run: |
          flatpak-builder --user --install --force-clean build-dir com.maxizamorano.photopea-no-ads.yml

      - name: Run Flatpak Application
        run: |
          flatpak run com.maxizamorano.photopea-no-ads
